# Generated by Django 4.2.24 on 2025-09-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskstatus',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='faultrecord',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faultrecord',
            name='sent_to_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='faultrecord',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fault_images/'),
        ),
    ]
