# Generated by Django 4.2.24 on 2025-09-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0002_alter_taskstatus_options_faultrecord_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faultrecord',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
