# Generated by Django 4.2.24 on 2025-09-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0004_faultrecord_fault_name_taskstatus_fault_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faultrecord',
            name='class_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
