# Generated by Django 4.2.24 on 2025-10-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0005_faultrecord_class_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faultrecord',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fault_images/'),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
