# Generated by Django 4.2.24 on 2025-10-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0006_alter_faultrecord_image_alter_taskstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faultrecord',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('resolved', 'Resolved')], default='pending', max_length=50),
        ),
    ]
