# Generated by Django 4.2.24 on 2025-10-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0007_alter_faultrecord_image_alter_taskstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='faultrecord',
            name='duplicate_images_removed',
            field=models.BooleanField(default=False),
        ),
    ]
