# Generated by Django 4.2.24 on 2025-11-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0008_faultrecord_duplicate_images_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='faultrecord',
            name='is_annotated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='faultrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('resolved', 'Resolved'), ('confirmed', 'Confirmed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('resolved', 'Resolved'), ('confirmed', 'Confirmed')], default='pending', max_length=50),
        ),
    ]
