# Generated by Django 4.2.24 on 2025-11-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0009_faultrecord_is_annotated_alter_faultrecord_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faultrecord',
            name='is_annotated',
        ),
        migrations.AlterField(
            model_name='faultrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('resolved', 'Resolved')], default='pending', max_length=50),
        ),
    ]
