# Generated by Django 4.2.24 on 2025-11-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0010_remove_faultrecord_is_annotated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faultrecord',
            name='ready_for_training',
            field=models.BooleanField(default=False),
        ),
    ]
