# Generated by Django 4.2.24 on 2025-11-22 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0011_faultrecord_ready_for_training'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faultrecord',
            name='ready_for_training',
        ),
    ]
